K = kernel
U = user

# Tools. Override the prefix for other toolchains, e.g.
#   make TOOLPREFIX=riscv64-unknown-elf-   (multilib GCC, as packaged by Debian/Ubuntu)
TOOLPREFIX ?= riscv32-unknown-elf-
CC = $(TOOLPREFIX)gcc
LD = $(CC)
OBJCOPY = $(TOOLPREFIX)objcopy
QEMU = qemu-system-riscv32
CPUS ?= 4

# Flags
ARCH = -march=rv32ima_zicsr -mabi=ilp32
CFLAGS = -ffreestanding -nostdlib -mcmodel=medany -O2 -g -Wall $(ARCH) -I$K -MMD -MP
LDFLAGS = -T $K/kernel.ld -nostdlib -ffreestanding $(ARCH) -Wl,--no-warn-rwx-segments

# Source Files
C_SRC = $K/main.c $K/uart.c $K/kprint.c $K/boot.c $K/csr.c $K/mem.c \
        $K/vm.c $K/trap.c $K/spinlock.c $K/gpr.c $K/rv.c $K/proc.c $K/syscall.c $K/exec.c
ASM_SRC = $K/boot_asm.S $K/kerneltrap.S $K/usertrap.S $K/usertrapret.S $K/swtch.S

# Object files
C_OBJ = $(C_SRC:.c=.o)
ASM_OBJ = $(ASM_SRC:.S=.o)
OBJ = $(ASM_OBJ) $(C_OBJ)

OUTPUT = kernel.elf
INITCODE_HEADER = $K/initcode.h

all: $(INITCODE_HEADER) $(OUTPUT)

# --- KERNEL BUILD RULES ---

$(OUTPUT): $(OBJ) $K/kernel.ld
	$(LD) $(LDFLAGS) -o $@ $(OBJ)

# Compile C files
$K/%.o: $K/%.c
	$(CC) $(CFLAGS) -c $< -o $@

# Compile Assembly files
$K/%.o: $K/%.S
	$(CC) $(CFLAGS) -c $< -o $@

# Explicit dependency: proc.c needs initcode.h to exist before compiling
$K/proc.o: $(INITCODE_HEADER)

# Header dependencies generated by -MMD
-include $(OBJ:.o=.d)

# --- USER PROGRAM BUILD RULES ---

# 1. Compile init.S to an object file
$U/init.o: $U/init.S
	@mkdir -p $U
	$(CC) $(CFLAGS) -c $< -o $@

# 2. Link to start at 0x1000 (User Entry Point)
# We don't use kernel.ld here; we just need the text section at 0x1000.
$U/init.elf: $U/init.o $U/user.ld
	$(LD) -nostdlib $(ARCH) -T $U/user.ld -o $@ $<

# 3. Strip ELF headers to create a flat binary
$U/init.bin: $U/init.elf
	$(OBJCOPY) -S -O binary $< $@

# 4. Build the second user program (exec's first target) the same way
$U/hello.o: $U/hello.S
	@mkdir -p $U
	$(CC) $(CFLAGS) -c $< -o $@

$U/hello.elf: $U/hello.o $U/user.ld
	$(LD) -nostdlib $(ARCH) -T $U/user.ld -o $@ $<

# 5. Convert the images to a C header (hex dump)
# Requires 'xxd' tool (standard on Linux/WSL). xxd names each array after the
# path: user/init.elf -> unsigned char user_init_elf[] + user_init_elf_len.
# Only the first line uses '>' (start a fresh file); the rest append with '>>'.
$(INITCODE_HEADER): $U/init.bin $U/init.elf $U/hello.elf
	xxd -i $U/init.bin > $@
	xxd -i $U/init.elf >> $@
	xxd -i $U/hello.elf >> $@

# --- RUN ---

QEMUOPTS = -machine virt -bios none -kernel $(OUTPUT) -nographic -serial mon:stdio -smp $(CPUS)

# Exit QEMU with Ctrl-A then X
qemu: all
	$(QEMU) $(QEMUOPTS)

# Waits for a debugger: in another terminal run
#   gdb -ex "target remote :1234" kernel.elf   (or riscv32-unknown-elf-gdb / gdb-multiarch)
qemu-gdb: all
	$(QEMU) $(QEMUOPTS) -s -S

# --- CLEAN ---

clean:
	rm -f $K/*.o $K/*.d $(OUTPUT) $(INITCODE_HEADER) $U/*.o $U/*.d $U/*.elf $U/*.bin

.PHONY: all clean qemu qemu-gdb
