#include <stdint.h>
#include "exec.h"
#include "kprint.h"
#include "mem.h"
#include "vm.h"
#include "spinlock.h"
#include "elf.h"
#include "uart.h"
#include "initcode.h"
#include "proc.h"

// No filesystem yet: user programs are ELF images embedded in the kernel
// (initcode.h, generated by the Makefile) and looked up by name in this table.
// initcode.h defines the arrays, so only this file may include it.
struct program {
    const char *name;
    const uint8_t *img;
    uint32_t len;
};

static const struct program programs[] = {
    { "init",  user_init_elf,  sizeof(user_init_elf)  },
    { "hello", user_hello_elf, sizeof(user_hello_elf) },
};

// Find the embedded program called name. On success points *img at its ELF
// bytes, sets *len to their length and returns 0; returns -1 if there is none.
int find_program(const char *name, const uint8_t **img, uint32_t *len) {
    int i;
    int table_count = sizeof(programs) / sizeof(programs[0]);
    for (i = 0; i < table_count; i++) {
        if (strcmp(name, programs[i].name) == 0) {
            *img = programs[i].img;
            *len = programs[i].len;
            return 0;
        }
    }
    return -1;
}

// Load the ELF executable img (len bytes long) into the fresh user page table pt.
// On success sets *entry (the program's first pc) and *sz (page-aligned end of
// the loaded image) and returns 0. Returns -1 if img is not a valid RV32
// executable or memory runs out; *sz then still says how far loading got, so
// the caller can free everything with uvmfree(pt, *sz).
int load_elf(pagetable_t pt, const uint8_t *img, uint32_t len, uint32_t *entry, uint32_t *sz) {
    struct elf_hdr elf;
    struct prg_hdr prg;
    uint32_t size = USER_BASE; // page 0 stays unmapped
    *sz = size;

    // Check the ELF header
    if (len < sizeof(struct elf_hdr)) return -1;
    memmove(&elf, img, sizeof(struct elf_hdr));
    if (elf.magic != ELF_MAGIC) return -1;
    if (elf.e_ident[0] != ELFCLASS32) return -1;
    if (elf.type != ET_EXEC) return -1;
    if (elf.machine != EM_RISCV) return -1;
    if (elf.phentsize != sizeof(struct prg_hdr)) return -1;

    // The program headers are a table of phnum entries, sizeof(struct prg_hdr)
    // bytes each, starting at byte phoff of the file. Each pass reads entry i.
    for (int i = 0; i < elf.phnum; i++) {
        uint32_t off = elf.phoff + i * sizeof(struct prg_hdr);
        if (off < elf.phoff || off + sizeof(struct prg_hdr) > len) return -1; // overflow or past end of file
        memmove(&prg, img + off, sizeof(struct prg_hdr)); // copy out: img may not be 4-byte aligned

        if (prg.type != PT_LOAD) continue;
        if (prg.memsz == 0) continue; // empty segment (e.g. no data at all): nothing to load
        if (prg.memsz < prg.filesz) return -1;
        if (prg.offset + prg.filesz < prg.offset || prg.offset + prg.filesz > len) return -1;
        if (prg.va % PAGE_SIZE != 0) return -1;
        if (prg.va < size) return -1; // overlaps an earlier segment: mappage() would panic on the remap
        // Must end inside user space: above it, every page table maps the UART and the kernel
        if (prg.va + prg.memsz < prg.va || prg.va + prg.memsz > UART_0) return -1;

        int perm = 0; // ELF flag bits differ from PTE bits; uvmalloc adds PTE_R | PTE_U
        if (prg.flags & PF_X) perm |= PTE_X;
        if (prg.flags & PF_W) perm |= PTE_W;
        uint32_t newsz = uvmalloc(pt, size, prg.va + prg.memsz, perm);
        if (newsz == 0) return -1;
        size = newsz;
        *sz = PGROUNDUP(size);

        // Copy the file bytes; the rest up to memsz (.bss) is already zero
        if (load_segment(pt, prg.va, img, prg.offset, prg.filesz) < 0) return -1;
    }

    *entry = elf.entry;
    *sz = PGROUNDUP(size);
    return 0;
}


// Load an ELF program segment into pagetable at virtual address va.
// va must be page-aligned
// and the pages from va to va+sz must already be mapped.
// Returns 0 on success, -1 on failure.
// pt already mapped
// va ph.vaddr
// img (LATER FILE READ)
// offset ph.offset
// sz ph.filesz
int load_segment(pagetable_t pt, uint32_t va, const uint8_t *img, uint32_t offset, uint32_t sz) {
    uint32_t pa;
    img += offset;
    while (sz > 0) {
        pa = find_pa(pt, va);
        if (pa == 0) {
            return -1;
        }
        uint32_t pgoff = pa % PAGE_SIZE;
        uint32_t n = PAGE_SIZE - pgoff;
        if (n > sz)
            n = sz;
        memmove((void *)(uintptr_t)pa, img, n);
        sz -= n;
        img += n;
        va += n;
    }
    return 0;
}

// Replace the calling process's program with the embedded program called path.
// The new address space is built on the side first; only once it is complete
// does the process switch to it and free the old one. So if anything fails,
// the caller is untouched and gets -1. argv is the kernel's copy of the
// arguments, ending with a 0 entry. On success returns argc, which syscall()
// puts in the new program's a0.
int kexec(const char *path, char **argv) {
    struct proc *p = myproc();
    const uint8_t *img;
    uint32_t len, sz, oldsz, entry;
    pagetable_t pt, oldpt;

    // Build the new address space
    if (find_program(path, &img, &len) == -1) return -1;
    pt = init_userpt();
    if (pt == NULL) return -1;
    if (load_elf(pt, img, len, &entry, &sz) == -1) goto bad; // sets sz even on failure

    void *stack = kalloc();
    if (stack == NULL) goto bad;
    memset(stack, 0, PAGE_SIZE); // kalloc doesn't zero: don't leak the old owner's data
    if (mappage(pt, USER_STACK_TOP - PAGE_SIZE, (uint32_t)stack, PTE_R | PTE_W | PTE_U) == 0) {
        kfree(stack); // not in pt yet, so uvmfree can't find it
        goto bad;
    }
    // Push the argument strings, then the argv array pointing at them, from
    // the top of the stack down. sp is kept 16-byte aligned: the RISC-V
    // calling convention requires it.
    uint32_t sp = USER_STACK_TOP, stackbase = USER_STACK_TOP - PAGE_SIZE;
    uint32_t ustack[MAXARG + 1]; // user addresses of the strings
    int argc;
    for (argc = 0; argv[argc] != 0; argc++) {
        if (argc >= MAXARG) goto bad;
        uint32_t n = strlen(argv[argc]) + 1; // include the '\0'
        sp -= n;
        sp &= ~0xF;
        if (sp < stackbase) goto bad; // doesn't fit in the stack page
        if (copyout(pt, sp, argv[argc], n) < 0) goto bad;
        ustack[argc] = sp;
    }
    ustack[argc] = 0; // argv ends with a null pointer
    sp -= (argc + 1) * sizeof(uint32_t);
    sp &= ~0xF;
    if (sp < stackbase) goto bad;
    if (copyout(pt, sp, (char *)ustack, (argc + 1) * sizeof(uint32_t)) < 0) goto bad;

    // Commit: from here on exec can't fail
    oldpt = p->pt;
    oldsz = p->sz;
    p->pt = pt;
    p->sz = sz;
    p->tf->epc = entry;
    p->tf->regs[2] = sp;  // sp
    p->tf->regs[11] = sp; // a1 = argv (the array is at the top of the stack)
    int i;
    for (i = 0; i < sizeof(p->name) - 1 && path[i] != '\0'; i++)
        p->name[i] = path[i];
    p->name[i] = '\0';

    // Free the old image. Safe: the kernel runs on kptable during a syscall,
    // and utrapret loads p->pt (now the new table) into satp on the way out.
    uvmfree(oldpt, oldsz);
    return argc; // syscall() stores it in a0

bad:
    uvmfree(pt, sz);
    return -1;
}
