#include "proc.h"
#include "kprint.h"
#include "syscall.h"
#include "trap.h"
// #include "fd.h"

uint32_t argraw(int n) {
    struct proc *p = myproc();
    switch(n) {
        case 0:
            return p->tf->regs[10];
        case 1:
            return p->tf->regs[11];
        case 2:
            return p->tf->regs[12];
        case 3:
            return p->tf->regs[13];
        case 4:
            return p->tf->regs[14];
        case 5:
            return p->tf->regs[15];
    }
    error("argraw");
    return -1;
}

// Retrieves argument
void argaddr(int n, uint32_t *ip) {
    *ip = argraw(n);
}

void argint(int n, int *ip) {
    *ip = argraw(n);
}

uint32_t sys_exit(){
    int status;
    argint(0, &status);
    kexit(status); // never returns
}

// Unimplemented syscalls fail with -1 rather than pretending to succeed.
uint32_t sys_open() {
    return -1;
}

uint32_t sys_wait() {
    uint32_t addr;
    argaddr(0, &addr);
    return wait(addr);
}

// TODO
uint32_t sys_exec() {

    // 1. Copy in the arguments. path and argv are user-space pointers in the caller's current (old) address space — pull them into kernel buffers via copyin before anything else changes, exactly like sys_write already does with its buffer.

    // char path[128], *argv[32]; // TODO: Change max args
    // int path_size;
    // uint32_t uargv, uarg;
    //
    // argaddr(1, &uargv);
    // argint(2, &path_size);
    // if (path_size > 127) return -1;

    // Get path
    


    // 2. Find the program image. There's no filesystem yet, so for now this has to come from somewhere embedded in the kernel — the same trick initcode.h already uses (user_init_bin/user_init_bin_len generated by the Makefile's xxd -i step). A small lookup table of {name, data, len} mapping path strings to embedded blobs is the natural stand-in until Milestone 4 (virtio + real fs) lands.

    // 3. Build a fresh page table, the same way procalloc() does via init_userpt() — gets you the kernel mappings, but nothing user-facing yet.

    // 4. Load the program into it — this step is literally what uvmfirst() already does for the very first process: kalloc() a page, memmove() the flat binary in, mappage() it at 0x1000 with PTE_R | PTE_X | PTE_U. (Worth noting: uvmfirst currently errors out if the binary is bigger than one page — sys_exec will hit that same ceiling immediately unless it's extended to loop over multiple pages.)

    // 5. Set up a fresh stack, same shape as uvmfirst's stack page — kalloc, zero it, mappage it at USER_STACK_TOP - PAGE_SIZE. If passing real argv, this is where it gets fiddly: push each argument string onto this new stack, build the argv[] pointer array above them, and land on a final sp pointing at that array — mirroring the calling convention _start in a real crt0.S would expect (a0 = argc, a1 = argv, matching how argraw/argint already read a0/a1 for every other syscall).

    // 6. Commit. Only now, with the new page table fully built and known-good:
    // Save the old p->pt and old p->sz aside.
    // Swap in the new one: p->pt = new_pt, p->sz = <new program size>.
    // Point the trapframe at the new program: p->tf->epc = 0x1000 (entry, fixed for these flat binaries), p->tf->regs[2] = <new sp>, and p->tf->regs[10]/regs[11] = argc/argv if passing arguments.
    // Free the old address space with uvmfree(old_pt, old_sz) — the same function sys_exit and releaseproc already use.


    // 7. Return. sys_exec returns argc on success (by convention); on any failure before step 6, just kfree/uvmfree whatever partial new-page-table state was built and return -1 — the caller's original image was never touched, so it just resumes as if the call had failed like any other syscall.

    return -1; // not implemented yet
}

uint32_t sys_fork() {
    return fork();
}

uint32_t sys_read() {
    return -1;
}

// TODO: sanity check, argument extraction, call k_write from fs.c
uint32_t sys_write() {
    int fd;
    uint32_t p_buf; // User Virtual Address
    int n;

    // Fetch Arguments
    argint(0, &fd);
    argaddr(1, &p_buf); // Fetches a0, a1, a2
    argint(2, &n);

    // Safety Checks
    if (fd != 1) return -1; // Only stdout supported for now
    if (n < 0 || n > 1024) return -1; // Safety cap

    // Allocate Kernel Buffer
    char kbuf[128]; 
    
    int wrote = 0;
    while (wrote < n) {
        int chunk = n - wrote;
        if (chunk > 127) chunk = 127; // Copy in small chunks

        // copy from User to Kernel
        if (copyin(myproc()->pt, kbuf, p_buf + wrote, chunk) == -1) {
            printf("sys_write: fault at %p\n", p_buf + wrote);
            return -1;
        }

        kbuf[chunk] = 0; // Null terminate for printf safety
        printf("%s", kbuf); // Send to UART
        wrote += chunk;
    }
    
    return n;
}

uint32_t sys_brk(){
    return -1;
}

uint32_t sys_kill(){
    return -1;
}

// sleep(n): put the caller to sleep for n clock ticks (n / TICK_HZ seconds),
// using no CPU meanwhile. clockintr() calls wakeup(&ticks) every tick, so the
// loop wakes once per tick, re-checks, and sleeps again until n have passed.
uint32_t sys_sleep(){
    int n;
    argint(0, &n);
    if (n < 0) return -1;

    lock(&tickslock);
    uint32_t start = ticks; // fixed: the moment the sleep began
    while (ticks - start < (uint32_t)n) { // unsigned subtraction: correct across wraparound
        sleep(&ticks, &tickslock);
    }
    unlock(&tickslock);
    return 0;
}

uint32_t sys_getpid() {
    return myproc()->pid;
}

// TODO(M1 step 7, optional): sys_uptime(): return ticks, read under
// tickslock. Handy for user programs to measure how long sleep() took.

static uint32_t (*syscalls[])(void) = {
    [SYS_EXIT]    = sys_exit,
    [SYS_OPEN]    = sys_open,
    [SYS_WAIT]    = sys_wait,
    [SYS_EXEC]    = sys_exec,
    [SYS_FORK]    = sys_fork,
    [SYS_READ]    = sys_read,
    [SYS_WRITE]   = sys_write,
    [SYS_BRK]     = sys_brk,
    [SYS_KILL]    = sys_kill,
    [SYS_GETPID]  = sys_getpid,
    [SYS_SLEEP]   = sys_sleep,
};


// Determine the type of syscall from a7 register
void syscall() {
    struct proc *p = myproc();
    int syscall_num = p->tf->regs[17]; // reference a7
    // printf("syscall_num a0 is %d\n", syscall_num);

    if (syscall_num <= 0 || syscall_num >= NSYSCALLS || syscalls[syscall_num] == 0) {
        printf("Error: Invalid syscall %d\n", syscall_num);
        p->tf->regs[10] = -1; // set a0 as -1 for return value
        return;
    }
    p->tf->regs[10] = syscalls[syscall_num](); // execute and store return value in a0
}